project:
  type: manuscript

manuscript:
  article: index.qmd
  
  notebooks:
  - notebook: notebooks/eda_orders.qmd
    title: EDA Orders
  - notebook: notebooks/eda_aisles.qmd
    title: EDA Aisles

  code-links:
    - text: GitHub
      icon: github
      href: https://github.com/ManuelLagunas/instacart.git

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



